

charm_config_tpl = """<!-- CONFIG STARTS -->
<!--AUTOGENERATED CONFIG TEXT - DO NOT EDIT -->


| name | type   | Default      | Description                               |
|------|--------|--------------|-------------------------------------------|
{% for c in sorted(options.items()) %}
| <a id="table-${c[0]}"> </a> ${c[0]} | ${c[1]['type']} | ${c[1]['default']} | ${c[1]['description']} |
{% end %}

---

{% for d in sorted(overmatter.items()) %}
### ${d[0]}

{% for i in d[1] %}

${i[0]}
**${i[1]}:**

${i[2]}

{% end %}

{% end %}

<!-- CONFIG ENDS -->
"""
