component_page_tpl ="""---
{{ frontmatter_text }}---

<!-- THIS PAGE IS AUTOGENERATED -->
<!-- If you find an error in this page, it is likely to be in the original
source of the information - please file a bug rather than editing the text -->

This page details the charms, snaps, images and other components
which go to make up the {{release}} release of Charmed Kubernetes.

Other information about this release can be found on the following pages:

 [documentation][]{: .p-button--neutral} [release notes][]{: .p-button--neutral}
 [upgrade notes][]{: .p-button--brand} [bugs][]{: .p-button--neutral}
 [source][]{: .p-button--neutral} [{{release}} milestone][]{: .p-button--neutral}

## Core charms

These charms are the core components or official optional components of the
release. These charms are maintained by the Charmed Kubernetes team.

{:.u-table-layout--auto}
| charm  | summary | docs | source | bugs | version | notes |
|--------|---------|------|--------|------|---------|-------|
{% for c in charms -%}
| {{c.name}} | {{c.summary.rstrip()}}| [docs](/kubernetes/docs/{{release}}/charm-{{c.name}}) | [source]({{c.source_url}}) | | |
{% endfor %}

## Snaps

The following snaps are used by this release of Charmed Kubernetes:

{:.u-table-layout--auto}
| snap  | confinement | summary | link |
|-------|-------------|---------|------|
{% for s in snaps.keys() -%}
|{{snaps[s]['Name']}}| ? | {{snaps[s]['Description']}} | ? |
{% endfor %}

<!-- LINKS -->
[documentation]: /kubernetes/docs/
[release notes]: /kubernetes/docs/release-notes#{{release}}
[upgrade notes]: /kubernetes/docs/
[bugs]: /kubernetes/docs/
[source]: https://github.com/charmed-kubernetes
[{{release}} milestone]: https://launchpad.net/charmed-kubernetes/+milestone/{{release}}


"""

charm_config_tpl = """<!-- CONFIG STARTS -->
<!--AUTOGENERATED CONFIG TEXT - DO NOT EDIT -->


| name | type   | Default      | Description                               |
|------|--------|--------------|-------------------------------------------|
{% for c in sorted(options.items()) %}
| <a id="table-${c[0]}"> </a> ${c[0]} | ${c[1]['type']} | ${c[1]['default']} | ${c[1]['description']} |
{% end %}

---

{% for d in sorted(overmatter.items()) %}
### ${d[0]}

{% for i in d[1] %}

${i[0]}
**${i[1]}:**

${i[2]}

{% end %}

{% end %}

<!-- CONFIG ENDS -->
"""



charm_config_tpl_2 = """<!-- CONFIG STARTS -->
<!--AUTOGENERATED CONFIG TEXT - DO NOT EDIT -->


| name | type   | Default      | Description                               |
|------|--------|--------------|-------------------------------------------|
{% for c in options.items()|sort %}
| <a id="table-{{c[0]}}"> </a> {{c[0]}} | {{c[1]['type']}} | {{c[1]['default']}} | {{c[1]['description']}} |
{% endfor %}

---

{% for d in overmatter.items()|sort %}
### {{d[0]}}

{% for i in d[1] %}

{{i[0]}}
**{{i[1]}}:**

{{i[2]}}

{% endfor %}

{% endfor %}

<!-- CONFIG ENDS -->
"""


frontmatter_tpl = {
'wrapper_template': 'kubernetes/docs/base_docs.html',
'markdown_includes': {'nav': 'kubernetes/docs/shared/_side-navigation.md'},
'context': {'title': 'Components', 'description': 'Detailed description of Charmed Kubernetes release'},
'keywords': 'component, charms, versions, release',
'tags': ['reference'],
'sidebar': 'k8smain-sidebar',
'permalink': '-',
'layout': ['base', 'ubuntu-com'],
'toc': False
}
